### ISSUE TITLE
Can't download latest binary

### ISSUE THREAD

**Issue by lauri-leirost** [getsandbox/sandbox#43]
Hi,

Trying to download the latest binary from https://s3.amazonaws.com/sandbox-binaries/runtime-binary.tar results in error with message:

```
<Error>
  <Code>NoSuchBucket</Code>
  <Message>The specified bucket does not exist</Message>
  <BucketName>sandbox-binaries</BucketName>
  <RequestId>49278F18813C8A91</RequestId>
  <HostId>...</HostId>
</Error>
```

**Comment by nhoughto** [comment]
Ah we’ve just migrated to GCS, must have missed a link 👍🏼
Thanks for the tip

**Comment by nhoughto** [comment]
Fixed

**Comment by orlandojsjr** [comment]
Hey guys,
@nhoughto what was the fix? I'm still getting the same error.

![image](https://user-images.githubusercontent.com/1436431/79667048-461e0b00-818c-11ea-8b5e-7e3e2905ef96.png)

And then: `https://sandbox-binaries.s3.amazonaws.com/sandbox-binaries/runtime-binary.tar`

![image](https://user-images.githubusercontent.com/1436431/79667919-84b3c580-818c-11ea-990a-6a687358eb8c.png)

**Comment by nhoughto** [comment]
Moved it to github releases instead of s3 bucket since we've moved off AWS :+1:

https://github.com/getsandbox/sandbox/releases
